server:
  type: default
  applicationContextPath: /
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: ${PORT:-8888}
  # disable admin
  adminConnectors: []
  # disable request logging
  requestLog:
    appenders: []

logging:
  level: INFO
  appenders:
    - type: console

metrics:
  frequency: 10 seconds

twilio:
  accountSid: ${TWILIO_ACCOUNT_SID:-}
  authToken: ${TWILIO_AUTH_TOKEN:-}
  phoneNumbers:
    - ${TWILIO_PHONE_NUMBER:-}

authentication:
  credentials:
    twilio: ${TWILIO_PASSWORD:-}

service:
  baseUri: https://ttyl-9000.herokuapp.com/api
