server:
  type: default
  applicationContextPath: /
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: ${PORT:-8888}
  # disable admin
  adminConnectors: []

httpClient: {}

representativeClient:
  baseUri: http://whoismyrepresentative.com/

logging:
  level: INFO
  appenders:
    - type: console

metrics:
  frequency: 10 seconds

twilio:
  accountSid: ${TWILIO_ACCOUNT_SID:-}
  authToken: ${TWILIO_AUTH_TOKEN:-}
  phoneNumber: ${TWILIO_PHONE_NUMBER:-}
