server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: ${PORT:-8888}

logging:
  level: INFO
  appenders:
    - type: console

metrics:
  frequency: 10 seconds

twilio:
  accountSid: ${TWILIO_ACCOUNT_SID:-}
  authToken: ${TWILIO_AUTH_TOKEN:-}
  phoneNumber: ${TWILIO_PHONE_NUMBER:-}
